# config/packages/messenger.yaml
framework:
    messenger:
        # This tells the mailer to send emails instantly, instead of queuing them.
        transports:
            async: 'sync://'

        routing:
            # Route your messages to the transports
            'Symfony\Component\Mailer\Messenger\SendEmailMessage': async